// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feedback.proto

#ifndef PROTOBUF_INCLUDED_feedback_2eproto
#define PROTOBUF_INCLUDED_feedback_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_feedback_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_feedback_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_feedback_2eproto();
namespace protos {
class CGFeedback;
class CGFeedbackDefaultTypeInternal;
extern CGFeedbackDefaultTypeInternal _CGFeedback_default_instance_;
class GCFeedback;
class GCFeedbackDefaultTypeInternal;
extern GCFeedbackDefaultTypeInternal _GCFeedback_default_instance_;
}  // namespace protos
namespace google {
namespace protobuf {
template<> ::protos::CGFeedback* Arena::CreateMaybeMessage<::protos::CGFeedback>(Arena*);
template<> ::protos::GCFeedback* Arena::CreateMaybeMessage<::protos::GCFeedback>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protos {

// ===================================================================

class CGFeedback :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.CGFeedback) */ {
 public:
  CGFeedback();
  virtual ~CGFeedback();

  CGFeedback(const CGFeedback& from);

  inline CGFeedback& operator=(const CGFeedback& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CGFeedback(CGFeedback&& from) noexcept
    : CGFeedback() {
    *this = ::std::move(from);
  }

  inline CGFeedback& operator=(CGFeedback&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CGFeedback& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CGFeedback* internal_default_instance() {
    return reinterpret_cast<const CGFeedback*>(
               &_CGFeedback_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CGFeedback* other);
  friend void swap(CGFeedback& a, CGFeedback& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CGFeedback* New() const final {
    return CreateMaybeMessage<CGFeedback>(nullptr);
  }

  CGFeedback* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CGFeedback>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CGFeedback& from);
  void MergeFrom(const CGFeedback& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CGFeedback* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string content = 2;
  void clear_content();
  static const int kContentFieldNumber = 2;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // int64 guid = 1;
  void clear_guid();
  static const int kGuidFieldNumber = 1;
  ::google::protobuf::int64 guid() const;
  void set_guid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:protos.CGFeedback)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  ::google::protobuf::int64 guid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_feedback_2eproto;
};
// -------------------------------------------------------------------

class GCFeedback :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.GCFeedback) */ {
 public:
  GCFeedback();
  virtual ~GCFeedback();

  GCFeedback(const GCFeedback& from);

  inline GCFeedback& operator=(const GCFeedback& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GCFeedback(GCFeedback&& from) noexcept
    : GCFeedback() {
    *this = ::std::move(from);
  }

  inline GCFeedback& operator=(GCFeedback&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GCFeedback& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GCFeedback* internal_default_instance() {
    return reinterpret_cast<const GCFeedback*>(
               &_GCFeedback_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GCFeedback* other);
  friend void swap(GCFeedback& a, GCFeedback& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GCFeedback* New() const final {
    return CreateMaybeMessage<GCFeedback>(nullptr);
  }

  GCFeedback* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GCFeedback>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GCFeedback& from);
  void MergeFrom(const GCFeedback& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GCFeedback* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 guid = 2;
  void clear_guid();
  static const int kGuidFieldNumber = 2;
  ::google::protobuf::int64 guid() const;
  void set_guid(::google::protobuf::int64 value);

  // int32 error = 1;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.GCFeedback)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 guid_;
  ::google::protobuf::int32 error_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_feedback_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CGFeedback

// int64 guid = 1;
inline void CGFeedback::clear_guid() {
  guid_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 CGFeedback::guid() const {
  // @@protoc_insertion_point(field_get:protos.CGFeedback.guid)
  return guid_;
}
inline void CGFeedback::set_guid(::google::protobuf::int64 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:protos.CGFeedback.guid)
}

// string content = 2;
inline void CGFeedback::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CGFeedback::content() const {
  // @@protoc_insertion_point(field_get:protos.CGFeedback.content)
  return content_.GetNoArena();
}
inline void CGFeedback::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.CGFeedback.content)
}
#if LANG_CXX11
inline void CGFeedback::set_content(::std::string&& value) {
  
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protos.CGFeedback.content)
}
#endif
inline void CGFeedback::set_content(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.CGFeedback.content)
}
inline void CGFeedback::set_content(const char* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.CGFeedback.content)
}
inline ::std::string* CGFeedback::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:protos.CGFeedback.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CGFeedback::release_content() {
  // @@protoc_insertion_point(field_release:protos.CGFeedback.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CGFeedback::set_allocated_content(::std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:protos.CGFeedback.content)
}

// -------------------------------------------------------------------

// GCFeedback

// int32 error = 1;
inline void GCFeedback::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 GCFeedback::error() const {
  // @@protoc_insertion_point(field_get:protos.GCFeedback.error)
  return error_;
}
inline void GCFeedback::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:protos.GCFeedback.error)
}

// int64 guid = 2;
inline void GCFeedback::clear_guid() {
  guid_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 GCFeedback::guid() const {
  // @@protoc_insertion_point(field_get:protos.GCFeedback.guid)
  return guid_;
}
inline void GCFeedback::set_guid(::google::protobuf::int64 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:protos.GCFeedback.guid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_feedback_2eproto
