// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta.proto

#ifndef PROTOBUF_INCLUDED_meta_2eproto
#define PROTOBUF_INCLUDED_meta_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_meta_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_meta_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[9]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_meta_2eproto();
namespace protos {
class G2GWSMeta;
class G2GWSMetaDefaultTypeInternal;
extern G2GWSMetaDefaultTypeInternal _G2GWSMeta_default_instance_;
class GWMeta;
class GWMetaDefaultTypeInternal;
extern GWMetaDefaultTypeInternal _GWMeta_default_instance_;
class GWRpcMeta;
class GWRpcMetaDefaultTypeInternal;
extern GWRpcMetaDefaultTypeInternal _GWRpcMeta_default_instance_;
class GWS2GMeta;
class GWS2GMetaDefaultTypeInternal;
extern GWS2GMetaDefaultTypeInternal _GWS2GMeta_default_instance_;
class GWS2GRpcMeta;
class GWS2GRpcMetaDefaultTypeInternal;
extern GWS2GRpcMetaDefaultTypeInternal _GWS2GRpcMeta_default_instance_;
class GWS2WMeta;
class GWS2WMetaDefaultTypeInternal;
extern GWS2WMetaDefaultTypeInternal _GWS2WMeta_default_instance_;
class GWS2WRpcMeta;
class GWS2WRpcMetaDefaultTypeInternal;
extern GWS2WRpcMetaDefaultTypeInternal _GWS2WRpcMeta_default_instance_;
class W2GWSMeta;
class W2GWSMetaDefaultTypeInternal;
extern W2GWSMetaDefaultTypeInternal _W2GWSMeta_default_instance_;
class WGMeta;
class WGMetaDefaultTypeInternal;
extern WGMetaDefaultTypeInternal _WGMeta_default_instance_;
}  // namespace protos
namespace google {
namespace protobuf {
template<> ::protos::G2GWSMeta* Arena::CreateMaybeMessage<::protos::G2GWSMeta>(Arena*);
template<> ::protos::GWMeta* Arena::CreateMaybeMessage<::protos::GWMeta>(Arena*);
template<> ::protos::GWRpcMeta* Arena::CreateMaybeMessage<::protos::GWRpcMeta>(Arena*);
template<> ::protos::GWS2GMeta* Arena::CreateMaybeMessage<::protos::GWS2GMeta>(Arena*);
template<> ::protos::GWS2GRpcMeta* Arena::CreateMaybeMessage<::protos::GWS2GRpcMeta>(Arena*);
template<> ::protos::GWS2WMeta* Arena::CreateMaybeMessage<::protos::GWS2WMeta>(Arena*);
template<> ::protos::GWS2WRpcMeta* Arena::CreateMaybeMessage<::protos::GWS2WRpcMeta>(Arena*);
template<> ::protos::W2GWSMeta* Arena::CreateMaybeMessage<::protos::W2GWSMeta>(Arena*);
template<> ::protos::WGMeta* Arena::CreateMaybeMessage<::protos::WGMeta>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protos {

// ===================================================================

class GWS2WMeta :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.GWS2WMeta) */ {
 public:
  GWS2WMeta();
  virtual ~GWS2WMeta();

  GWS2WMeta(const GWS2WMeta& from);

  inline GWS2WMeta& operator=(const GWS2WMeta& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GWS2WMeta(GWS2WMeta&& from) noexcept
    : GWS2WMeta() {
    *this = ::std::move(from);
  }

  inline GWS2WMeta& operator=(GWS2WMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GWS2WMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GWS2WMeta* internal_default_instance() {
    return reinterpret_cast<const GWS2WMeta*>(
               &_GWS2WMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GWS2WMeta* other);
  friend void swap(GWS2WMeta& a, GWS2WMeta& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GWS2WMeta* New() const final {
    return CreateMaybeMessage<GWS2WMeta>(nullptr);
  }

  GWS2WMeta* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GWS2WMeta>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GWS2WMeta& from);
  void MergeFrom(const GWS2WMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GWS2WMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 guid = 1;
  void clear_guid();
  static const int kGuidFieldNumber = 1;
  ::google::protobuf::int64 guid() const;
  void set_guid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:protos.GWS2WMeta)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 guid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_meta_2eproto;
};
// -------------------------------------------------------------------

class W2GWSMeta :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.W2GWSMeta) */ {
 public:
  W2GWSMeta();
  virtual ~W2GWSMeta();

  W2GWSMeta(const W2GWSMeta& from);

  inline W2GWSMeta& operator=(const W2GWSMeta& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  W2GWSMeta(W2GWSMeta&& from) noexcept
    : W2GWSMeta() {
    *this = ::std::move(from);
  }

  inline W2GWSMeta& operator=(W2GWSMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const W2GWSMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const W2GWSMeta* internal_default_instance() {
    return reinterpret_cast<const W2GWSMeta*>(
               &_W2GWSMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(W2GWSMeta* other);
  friend void swap(W2GWSMeta& a, W2GWSMeta& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline W2GWSMeta* New() const final {
    return CreateMaybeMessage<W2GWSMeta>(nullptr);
  }

  W2GWSMeta* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<W2GWSMeta>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const W2GWSMeta& from);
  void MergeFrom(const W2GWSMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(W2GWSMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 guids = 2;
  int guids_size() const;
  void clear_guids();
  static const int kGuidsFieldNumber = 2;
  ::google::protobuf::int64 guids(int index) const;
  void set_guids(int index, ::google::protobuf::int64 value);
  void add_guids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      guids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_guids();

  // repeated int64 group_ids = 4;
  int group_ids_size() const;
  void clear_group_ids();
  static const int kGroupIdsFieldNumber = 4;
  ::google::protobuf::int64 group_ids(int index) const;
  void set_group_ids(int index, ::google::protobuf::int64 value);
  void add_group_ids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      group_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_group_ids();

  // int64 guid = 1;
  void clear_guid();
  static const int kGuidFieldNumber = 1;
  ::google::protobuf::int64 guid() const;
  void set_guid(::google::protobuf::int64 value);

  // int64 group_id = 3;
  void clear_group_id();
  static const int kGroupIdFieldNumber = 3;
  ::google::protobuf::int64 group_id() const;
  void set_group_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:protos.W2GWSMeta)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > guids_;
  mutable std::atomic<int> _guids_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > group_ids_;
  mutable std::atomic<int> _group_ids_cached_byte_size_;
  ::google::protobuf::int64 guid_;
  ::google::protobuf::int64 group_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_meta_2eproto;
};
// -------------------------------------------------------------------

class GWS2WRpcMeta :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.GWS2WRpcMeta) */ {
 public:
  GWS2WRpcMeta();
  virtual ~GWS2WRpcMeta();

  GWS2WRpcMeta(const GWS2WRpcMeta& from);

  inline GWS2WRpcMeta& operator=(const GWS2WRpcMeta& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GWS2WRpcMeta(GWS2WRpcMeta&& from) noexcept
    : GWS2WRpcMeta() {
    *this = ::std::move(from);
  }

  inline GWS2WRpcMeta& operator=(GWS2WRpcMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GWS2WRpcMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GWS2WRpcMeta* internal_default_instance() {
    return reinterpret_cast<const GWS2WRpcMeta*>(
               &_GWS2WRpcMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(GWS2WRpcMeta* other);
  friend void swap(GWS2WRpcMeta& a, GWS2WRpcMeta& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GWS2WRpcMeta* New() const final {
    return CreateMaybeMessage<GWS2WRpcMeta>(nullptr);
  }

  GWS2WRpcMeta* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GWS2WRpcMeta>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GWS2WRpcMeta& from);
  void MergeFrom(const GWS2WRpcMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GWS2WRpcMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .protos.GWS2WMeta req = 1;
  bool has_req() const;
  void clear_req();
  static const int kReqFieldNumber = 1;
  const ::protos::GWS2WMeta& req() const;
  ::protos::GWS2WMeta* release_req();
  ::protos::GWS2WMeta* mutable_req();
  void set_allocated_req(::protos::GWS2WMeta* req);

  // .protos.W2GWSMeta resp = 2;
  bool has_resp() const;
  void clear_resp();
  static const int kRespFieldNumber = 2;
  const ::protos::W2GWSMeta& resp() const;
  ::protos::W2GWSMeta* release_resp();
  ::protos::W2GWSMeta* mutable_resp();
  void set_allocated_resp(::protos::W2GWSMeta* resp);

  // @@protoc_insertion_point(class_scope:protos.GWS2WRpcMeta)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::protos::GWS2WMeta* req_;
  ::protos::W2GWSMeta* resp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_meta_2eproto;
};
// -------------------------------------------------------------------

class GWS2GMeta :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.GWS2GMeta) */ {
 public:
  GWS2GMeta();
  virtual ~GWS2GMeta();

  GWS2GMeta(const GWS2GMeta& from);

  inline GWS2GMeta& operator=(const GWS2GMeta& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GWS2GMeta(GWS2GMeta&& from) noexcept
    : GWS2GMeta() {
    *this = ::std::move(from);
  }

  inline GWS2GMeta& operator=(GWS2GMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GWS2GMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GWS2GMeta* internal_default_instance() {
    return reinterpret_cast<const GWS2GMeta*>(
               &_GWS2GMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(GWS2GMeta* other);
  friend void swap(GWS2GMeta& a, GWS2GMeta& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GWS2GMeta* New() const final {
    return CreateMaybeMessage<GWS2GMeta>(nullptr);
  }

  GWS2GMeta* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GWS2GMeta>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GWS2GMeta& from);
  void MergeFrom(const GWS2GMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GWS2GMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 guid = 1;
  void clear_guid();
  static const int kGuidFieldNumber = 1;
  ::google::protobuf::int64 guid() const;
  void set_guid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:protos.GWS2GMeta)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 guid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_meta_2eproto;
};
// -------------------------------------------------------------------

class G2GWSMeta :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.G2GWSMeta) */ {
 public:
  G2GWSMeta();
  virtual ~G2GWSMeta();

  G2GWSMeta(const G2GWSMeta& from);

  inline G2GWSMeta& operator=(const G2GWSMeta& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  G2GWSMeta(G2GWSMeta&& from) noexcept
    : G2GWSMeta() {
    *this = ::std::move(from);
  }

  inline G2GWSMeta& operator=(G2GWSMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const G2GWSMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const G2GWSMeta* internal_default_instance() {
    return reinterpret_cast<const G2GWSMeta*>(
               &_G2GWSMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(G2GWSMeta* other);
  friend void swap(G2GWSMeta& a, G2GWSMeta& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline G2GWSMeta* New() const final {
    return CreateMaybeMessage<G2GWSMeta>(nullptr);
  }

  G2GWSMeta* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<G2GWSMeta>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const G2GWSMeta& from);
  void MergeFrom(const G2GWSMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(G2GWSMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 guids = 2;
  int guids_size() const;
  void clear_guids();
  static const int kGuidsFieldNumber = 2;
  ::google::protobuf::int64 guids(int index) const;
  void set_guids(int index, ::google::protobuf::int64 value);
  void add_guids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      guids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_guids();

  // repeated int64 group_ids = 4;
  int group_ids_size() const;
  void clear_group_ids();
  static const int kGroupIdsFieldNumber = 4;
  ::google::protobuf::int64 group_ids(int index) const;
  void set_group_ids(int index, ::google::protobuf::int64 value);
  void add_group_ids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      group_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_group_ids();

  // int64 guid = 1;
  void clear_guid();
  static const int kGuidFieldNumber = 1;
  ::google::protobuf::int64 guid() const;
  void set_guid(::google::protobuf::int64 value);

  // int64 group_id = 3;
  void clear_group_id();
  static const int kGroupIdFieldNumber = 3;
  ::google::protobuf::int64 group_id() const;
  void set_group_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:protos.G2GWSMeta)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > guids_;
  mutable std::atomic<int> _guids_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > group_ids_;
  mutable std::atomic<int> _group_ids_cached_byte_size_;
  ::google::protobuf::int64 guid_;
  ::google::protobuf::int64 group_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_meta_2eproto;
};
// -------------------------------------------------------------------

class GWS2GRpcMeta :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.GWS2GRpcMeta) */ {
 public:
  GWS2GRpcMeta();
  virtual ~GWS2GRpcMeta();

  GWS2GRpcMeta(const GWS2GRpcMeta& from);

  inline GWS2GRpcMeta& operator=(const GWS2GRpcMeta& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GWS2GRpcMeta(GWS2GRpcMeta&& from) noexcept
    : GWS2GRpcMeta() {
    *this = ::std::move(from);
  }

  inline GWS2GRpcMeta& operator=(GWS2GRpcMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GWS2GRpcMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GWS2GRpcMeta* internal_default_instance() {
    return reinterpret_cast<const GWS2GRpcMeta*>(
               &_GWS2GRpcMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(GWS2GRpcMeta* other);
  friend void swap(GWS2GRpcMeta& a, GWS2GRpcMeta& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GWS2GRpcMeta* New() const final {
    return CreateMaybeMessage<GWS2GRpcMeta>(nullptr);
  }

  GWS2GRpcMeta* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GWS2GRpcMeta>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GWS2GRpcMeta& from);
  void MergeFrom(const GWS2GRpcMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GWS2GRpcMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .protos.GWS2GMeta req = 1;
  bool has_req() const;
  void clear_req();
  static const int kReqFieldNumber = 1;
  const ::protos::GWS2GMeta& req() const;
  ::protos::GWS2GMeta* release_req();
  ::protos::GWS2GMeta* mutable_req();
  void set_allocated_req(::protos::GWS2GMeta* req);

  // .protos.G2GWSMeta resp = 2;
  bool has_resp() const;
  void clear_resp();
  static const int kRespFieldNumber = 2;
  const ::protos::G2GWSMeta& resp() const;
  ::protos::G2GWSMeta* release_resp();
  ::protos::G2GWSMeta* mutable_resp();
  void set_allocated_resp(::protos::G2GWSMeta* resp);

  // @@protoc_insertion_point(class_scope:protos.GWS2GRpcMeta)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::protos::GWS2GMeta* req_;
  ::protos::G2GWSMeta* resp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_meta_2eproto;
};
// -------------------------------------------------------------------

class GWMeta :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.GWMeta) */ {
 public:
  GWMeta();
  virtual ~GWMeta();

  GWMeta(const GWMeta& from);

  inline GWMeta& operator=(const GWMeta& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GWMeta(GWMeta&& from) noexcept
    : GWMeta() {
    *this = ::std::move(from);
  }

  inline GWMeta& operator=(GWMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GWMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GWMeta* internal_default_instance() {
    return reinterpret_cast<const GWMeta*>(
               &_GWMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(GWMeta* other);
  friend void swap(GWMeta& a, GWMeta& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GWMeta* New() const final {
    return CreateMaybeMessage<GWMeta>(nullptr);
  }

  GWMeta* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GWMeta>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GWMeta& from);
  void MergeFrom(const GWMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GWMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 guid = 1;
  void clear_guid();
  static const int kGuidFieldNumber = 1;
  ::google::protobuf::int64 guid() const;
  void set_guid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:protos.GWMeta)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 guid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_meta_2eproto;
};
// -------------------------------------------------------------------

class WGMeta :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.WGMeta) */ {
 public:
  WGMeta();
  virtual ~WGMeta();

  WGMeta(const WGMeta& from);

  inline WGMeta& operator=(const WGMeta& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WGMeta(WGMeta&& from) noexcept
    : WGMeta() {
    *this = ::std::move(from);
  }

  inline WGMeta& operator=(WGMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const WGMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WGMeta* internal_default_instance() {
    return reinterpret_cast<const WGMeta*>(
               &_WGMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(WGMeta* other);
  friend void swap(WGMeta& a, WGMeta& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WGMeta* New() const final {
    return CreateMaybeMessage<WGMeta>(nullptr);
  }

  WGMeta* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WGMeta>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WGMeta& from);
  void MergeFrom(const WGMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WGMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 guids = 2;
  int guids_size() const;
  void clear_guids();
  static const int kGuidsFieldNumber = 2;
  ::google::protobuf::int64 guids(int index) const;
  void set_guids(int index, ::google::protobuf::int64 value);
  void add_guids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      guids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_guids();

  // int64 guid = 1;
  void clear_guid();
  static const int kGuidFieldNumber = 1;
  ::google::protobuf::int64 guid() const;
  void set_guid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:protos.WGMeta)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > guids_;
  mutable std::atomic<int> _guids_cached_byte_size_;
  ::google::protobuf::int64 guid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_meta_2eproto;
};
// -------------------------------------------------------------------

class GWRpcMeta :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.GWRpcMeta) */ {
 public:
  GWRpcMeta();
  virtual ~GWRpcMeta();

  GWRpcMeta(const GWRpcMeta& from);

  inline GWRpcMeta& operator=(const GWRpcMeta& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GWRpcMeta(GWRpcMeta&& from) noexcept
    : GWRpcMeta() {
    *this = ::std::move(from);
  }

  inline GWRpcMeta& operator=(GWRpcMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GWRpcMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GWRpcMeta* internal_default_instance() {
    return reinterpret_cast<const GWRpcMeta*>(
               &_GWRpcMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(GWRpcMeta* other);
  friend void swap(GWRpcMeta& a, GWRpcMeta& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GWRpcMeta* New() const final {
    return CreateMaybeMessage<GWRpcMeta>(nullptr);
  }

  GWRpcMeta* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GWRpcMeta>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GWRpcMeta& from);
  void MergeFrom(const GWRpcMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GWRpcMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .protos.GWMeta req = 1;
  bool has_req() const;
  void clear_req();
  static const int kReqFieldNumber = 1;
  const ::protos::GWMeta& req() const;
  ::protos::GWMeta* release_req();
  ::protos::GWMeta* mutable_req();
  void set_allocated_req(::protos::GWMeta* req);

  // .protos.WGMeta resp = 2;
  bool has_resp() const;
  void clear_resp();
  static const int kRespFieldNumber = 2;
  const ::protos::WGMeta& resp() const;
  ::protos::WGMeta* release_resp();
  ::protos::WGMeta* mutable_resp();
  void set_allocated_resp(::protos::WGMeta* resp);

  // @@protoc_insertion_point(class_scope:protos.GWRpcMeta)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::protos::GWMeta* req_;
  ::protos::WGMeta* resp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_meta_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GWS2WMeta

// int64 guid = 1;
inline void GWS2WMeta::clear_guid() {
  guid_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 GWS2WMeta::guid() const {
  // @@protoc_insertion_point(field_get:protos.GWS2WMeta.guid)
  return guid_;
}
inline void GWS2WMeta::set_guid(::google::protobuf::int64 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:protos.GWS2WMeta.guid)
}

// -------------------------------------------------------------------

// W2GWSMeta

// int64 guid = 1;
inline void W2GWSMeta::clear_guid() {
  guid_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 W2GWSMeta::guid() const {
  // @@protoc_insertion_point(field_get:protos.W2GWSMeta.guid)
  return guid_;
}
inline void W2GWSMeta::set_guid(::google::protobuf::int64 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:protos.W2GWSMeta.guid)
}

// repeated int64 guids = 2;
inline int W2GWSMeta::guids_size() const {
  return guids_.size();
}
inline void W2GWSMeta::clear_guids() {
  guids_.Clear();
}
inline ::google::protobuf::int64 W2GWSMeta::guids(int index) const {
  // @@protoc_insertion_point(field_get:protos.W2GWSMeta.guids)
  return guids_.Get(index);
}
inline void W2GWSMeta::set_guids(int index, ::google::protobuf::int64 value) {
  guids_.Set(index, value);
  // @@protoc_insertion_point(field_set:protos.W2GWSMeta.guids)
}
inline void W2GWSMeta::add_guids(::google::protobuf::int64 value) {
  guids_.Add(value);
  // @@protoc_insertion_point(field_add:protos.W2GWSMeta.guids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
W2GWSMeta::guids() const {
  // @@protoc_insertion_point(field_list:protos.W2GWSMeta.guids)
  return guids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
W2GWSMeta::mutable_guids() {
  // @@protoc_insertion_point(field_mutable_list:protos.W2GWSMeta.guids)
  return &guids_;
}

// int64 group_id = 3;
inline void W2GWSMeta::clear_group_id() {
  group_id_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 W2GWSMeta::group_id() const {
  // @@protoc_insertion_point(field_get:protos.W2GWSMeta.group_id)
  return group_id_;
}
inline void W2GWSMeta::set_group_id(::google::protobuf::int64 value) {
  
  group_id_ = value;
  // @@protoc_insertion_point(field_set:protos.W2GWSMeta.group_id)
}

// repeated int64 group_ids = 4;
inline int W2GWSMeta::group_ids_size() const {
  return group_ids_.size();
}
inline void W2GWSMeta::clear_group_ids() {
  group_ids_.Clear();
}
inline ::google::protobuf::int64 W2GWSMeta::group_ids(int index) const {
  // @@protoc_insertion_point(field_get:protos.W2GWSMeta.group_ids)
  return group_ids_.Get(index);
}
inline void W2GWSMeta::set_group_ids(int index, ::google::protobuf::int64 value) {
  group_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:protos.W2GWSMeta.group_ids)
}
inline void W2GWSMeta::add_group_ids(::google::protobuf::int64 value) {
  group_ids_.Add(value);
  // @@protoc_insertion_point(field_add:protos.W2GWSMeta.group_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
W2GWSMeta::group_ids() const {
  // @@protoc_insertion_point(field_list:protos.W2GWSMeta.group_ids)
  return group_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
W2GWSMeta::mutable_group_ids() {
  // @@protoc_insertion_point(field_mutable_list:protos.W2GWSMeta.group_ids)
  return &group_ids_;
}

// -------------------------------------------------------------------

// GWS2WRpcMeta

// .protos.GWS2WMeta req = 1;
inline bool GWS2WRpcMeta::has_req() const {
  return this != internal_default_instance() && req_ != nullptr;
}
inline void GWS2WRpcMeta::clear_req() {
  if (GetArenaNoVirtual() == nullptr && req_ != nullptr) {
    delete req_;
  }
  req_ = nullptr;
}
inline const ::protos::GWS2WMeta& GWS2WRpcMeta::req() const {
  const ::protos::GWS2WMeta* p = req_;
  // @@protoc_insertion_point(field_get:protos.GWS2WRpcMeta.req)
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::GWS2WMeta*>(
      &::protos::_GWS2WMeta_default_instance_);
}
inline ::protos::GWS2WMeta* GWS2WRpcMeta::release_req() {
  // @@protoc_insertion_point(field_release:protos.GWS2WRpcMeta.req)
  
  ::protos::GWS2WMeta* temp = req_;
  req_ = nullptr;
  return temp;
}
inline ::protos::GWS2WMeta* GWS2WRpcMeta::mutable_req() {
  
  if (req_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::GWS2WMeta>(GetArenaNoVirtual());
    req_ = p;
  }
  // @@protoc_insertion_point(field_mutable:protos.GWS2WRpcMeta.req)
  return req_;
}
inline void GWS2WRpcMeta::set_allocated_req(::protos::GWS2WMeta* req) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete req_;
  }
  if (req) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      req = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, req, submessage_arena);
    }
    
  } else {
    
  }
  req_ = req;
  // @@protoc_insertion_point(field_set_allocated:protos.GWS2WRpcMeta.req)
}

// .protos.W2GWSMeta resp = 2;
inline bool GWS2WRpcMeta::has_resp() const {
  return this != internal_default_instance() && resp_ != nullptr;
}
inline void GWS2WRpcMeta::clear_resp() {
  if (GetArenaNoVirtual() == nullptr && resp_ != nullptr) {
    delete resp_;
  }
  resp_ = nullptr;
}
inline const ::protos::W2GWSMeta& GWS2WRpcMeta::resp() const {
  const ::protos::W2GWSMeta* p = resp_;
  // @@protoc_insertion_point(field_get:protos.GWS2WRpcMeta.resp)
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::W2GWSMeta*>(
      &::protos::_W2GWSMeta_default_instance_);
}
inline ::protos::W2GWSMeta* GWS2WRpcMeta::release_resp() {
  // @@protoc_insertion_point(field_release:protos.GWS2WRpcMeta.resp)
  
  ::protos::W2GWSMeta* temp = resp_;
  resp_ = nullptr;
  return temp;
}
inline ::protos::W2GWSMeta* GWS2WRpcMeta::mutable_resp() {
  
  if (resp_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::W2GWSMeta>(GetArenaNoVirtual());
    resp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:protos.GWS2WRpcMeta.resp)
  return resp_;
}
inline void GWS2WRpcMeta::set_allocated_resp(::protos::W2GWSMeta* resp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete resp_;
  }
  if (resp) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      resp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, resp, submessage_arena);
    }
    
  } else {
    
  }
  resp_ = resp;
  // @@protoc_insertion_point(field_set_allocated:protos.GWS2WRpcMeta.resp)
}

// -------------------------------------------------------------------

// GWS2GMeta

// int64 guid = 1;
inline void GWS2GMeta::clear_guid() {
  guid_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 GWS2GMeta::guid() const {
  // @@protoc_insertion_point(field_get:protos.GWS2GMeta.guid)
  return guid_;
}
inline void GWS2GMeta::set_guid(::google::protobuf::int64 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:protos.GWS2GMeta.guid)
}

// -------------------------------------------------------------------

// G2GWSMeta

// int64 guid = 1;
inline void G2GWSMeta::clear_guid() {
  guid_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 G2GWSMeta::guid() const {
  // @@protoc_insertion_point(field_get:protos.G2GWSMeta.guid)
  return guid_;
}
inline void G2GWSMeta::set_guid(::google::protobuf::int64 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:protos.G2GWSMeta.guid)
}

// repeated int64 guids = 2;
inline int G2GWSMeta::guids_size() const {
  return guids_.size();
}
inline void G2GWSMeta::clear_guids() {
  guids_.Clear();
}
inline ::google::protobuf::int64 G2GWSMeta::guids(int index) const {
  // @@protoc_insertion_point(field_get:protos.G2GWSMeta.guids)
  return guids_.Get(index);
}
inline void G2GWSMeta::set_guids(int index, ::google::protobuf::int64 value) {
  guids_.Set(index, value);
  // @@protoc_insertion_point(field_set:protos.G2GWSMeta.guids)
}
inline void G2GWSMeta::add_guids(::google::protobuf::int64 value) {
  guids_.Add(value);
  // @@protoc_insertion_point(field_add:protos.G2GWSMeta.guids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
G2GWSMeta::guids() const {
  // @@protoc_insertion_point(field_list:protos.G2GWSMeta.guids)
  return guids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
G2GWSMeta::mutable_guids() {
  // @@protoc_insertion_point(field_mutable_list:protos.G2GWSMeta.guids)
  return &guids_;
}

// int64 group_id = 3;
inline void G2GWSMeta::clear_group_id() {
  group_id_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 G2GWSMeta::group_id() const {
  // @@protoc_insertion_point(field_get:protos.G2GWSMeta.group_id)
  return group_id_;
}
inline void G2GWSMeta::set_group_id(::google::protobuf::int64 value) {
  
  group_id_ = value;
  // @@protoc_insertion_point(field_set:protos.G2GWSMeta.group_id)
}

// repeated int64 group_ids = 4;
inline int G2GWSMeta::group_ids_size() const {
  return group_ids_.size();
}
inline void G2GWSMeta::clear_group_ids() {
  group_ids_.Clear();
}
inline ::google::protobuf::int64 G2GWSMeta::group_ids(int index) const {
  // @@protoc_insertion_point(field_get:protos.G2GWSMeta.group_ids)
  return group_ids_.Get(index);
}
inline void G2GWSMeta::set_group_ids(int index, ::google::protobuf::int64 value) {
  group_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:protos.G2GWSMeta.group_ids)
}
inline void G2GWSMeta::add_group_ids(::google::protobuf::int64 value) {
  group_ids_.Add(value);
  // @@protoc_insertion_point(field_add:protos.G2GWSMeta.group_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
G2GWSMeta::group_ids() const {
  // @@protoc_insertion_point(field_list:protos.G2GWSMeta.group_ids)
  return group_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
G2GWSMeta::mutable_group_ids() {
  // @@protoc_insertion_point(field_mutable_list:protos.G2GWSMeta.group_ids)
  return &group_ids_;
}

// -------------------------------------------------------------------

// GWS2GRpcMeta

// .protos.GWS2GMeta req = 1;
inline bool GWS2GRpcMeta::has_req() const {
  return this != internal_default_instance() && req_ != nullptr;
}
inline void GWS2GRpcMeta::clear_req() {
  if (GetArenaNoVirtual() == nullptr && req_ != nullptr) {
    delete req_;
  }
  req_ = nullptr;
}
inline const ::protos::GWS2GMeta& GWS2GRpcMeta::req() const {
  const ::protos::GWS2GMeta* p = req_;
  // @@protoc_insertion_point(field_get:protos.GWS2GRpcMeta.req)
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::GWS2GMeta*>(
      &::protos::_GWS2GMeta_default_instance_);
}
inline ::protos::GWS2GMeta* GWS2GRpcMeta::release_req() {
  // @@protoc_insertion_point(field_release:protos.GWS2GRpcMeta.req)
  
  ::protos::GWS2GMeta* temp = req_;
  req_ = nullptr;
  return temp;
}
inline ::protos::GWS2GMeta* GWS2GRpcMeta::mutable_req() {
  
  if (req_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::GWS2GMeta>(GetArenaNoVirtual());
    req_ = p;
  }
  // @@protoc_insertion_point(field_mutable:protos.GWS2GRpcMeta.req)
  return req_;
}
inline void GWS2GRpcMeta::set_allocated_req(::protos::GWS2GMeta* req) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete req_;
  }
  if (req) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      req = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, req, submessage_arena);
    }
    
  } else {
    
  }
  req_ = req;
  // @@protoc_insertion_point(field_set_allocated:protos.GWS2GRpcMeta.req)
}

// .protos.G2GWSMeta resp = 2;
inline bool GWS2GRpcMeta::has_resp() const {
  return this != internal_default_instance() && resp_ != nullptr;
}
inline void GWS2GRpcMeta::clear_resp() {
  if (GetArenaNoVirtual() == nullptr && resp_ != nullptr) {
    delete resp_;
  }
  resp_ = nullptr;
}
inline const ::protos::G2GWSMeta& GWS2GRpcMeta::resp() const {
  const ::protos::G2GWSMeta* p = resp_;
  // @@protoc_insertion_point(field_get:protos.GWS2GRpcMeta.resp)
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::G2GWSMeta*>(
      &::protos::_G2GWSMeta_default_instance_);
}
inline ::protos::G2GWSMeta* GWS2GRpcMeta::release_resp() {
  // @@protoc_insertion_point(field_release:protos.GWS2GRpcMeta.resp)
  
  ::protos::G2GWSMeta* temp = resp_;
  resp_ = nullptr;
  return temp;
}
inline ::protos::G2GWSMeta* GWS2GRpcMeta::mutable_resp() {
  
  if (resp_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::G2GWSMeta>(GetArenaNoVirtual());
    resp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:protos.GWS2GRpcMeta.resp)
  return resp_;
}
inline void GWS2GRpcMeta::set_allocated_resp(::protos::G2GWSMeta* resp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete resp_;
  }
  if (resp) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      resp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, resp, submessage_arena);
    }
    
  } else {
    
  }
  resp_ = resp;
  // @@protoc_insertion_point(field_set_allocated:protos.GWS2GRpcMeta.resp)
}

// -------------------------------------------------------------------

// GWMeta

// int64 guid = 1;
inline void GWMeta::clear_guid() {
  guid_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 GWMeta::guid() const {
  // @@protoc_insertion_point(field_get:protos.GWMeta.guid)
  return guid_;
}
inline void GWMeta::set_guid(::google::protobuf::int64 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:protos.GWMeta.guid)
}

// -------------------------------------------------------------------

// WGMeta

// int64 guid = 1;
inline void WGMeta::clear_guid() {
  guid_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 WGMeta::guid() const {
  // @@protoc_insertion_point(field_get:protos.WGMeta.guid)
  return guid_;
}
inline void WGMeta::set_guid(::google::protobuf::int64 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:protos.WGMeta.guid)
}

// repeated int64 guids = 2;
inline int WGMeta::guids_size() const {
  return guids_.size();
}
inline void WGMeta::clear_guids() {
  guids_.Clear();
}
inline ::google::protobuf::int64 WGMeta::guids(int index) const {
  // @@protoc_insertion_point(field_get:protos.WGMeta.guids)
  return guids_.Get(index);
}
inline void WGMeta::set_guids(int index, ::google::protobuf::int64 value) {
  guids_.Set(index, value);
  // @@protoc_insertion_point(field_set:protos.WGMeta.guids)
}
inline void WGMeta::add_guids(::google::protobuf::int64 value) {
  guids_.Add(value);
  // @@protoc_insertion_point(field_add:protos.WGMeta.guids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
WGMeta::guids() const {
  // @@protoc_insertion_point(field_list:protos.WGMeta.guids)
  return guids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
WGMeta::mutable_guids() {
  // @@protoc_insertion_point(field_mutable_list:protos.WGMeta.guids)
  return &guids_;
}

// -------------------------------------------------------------------

// GWRpcMeta

// .protos.GWMeta req = 1;
inline bool GWRpcMeta::has_req() const {
  return this != internal_default_instance() && req_ != nullptr;
}
inline void GWRpcMeta::clear_req() {
  if (GetArenaNoVirtual() == nullptr && req_ != nullptr) {
    delete req_;
  }
  req_ = nullptr;
}
inline const ::protos::GWMeta& GWRpcMeta::req() const {
  const ::protos::GWMeta* p = req_;
  // @@protoc_insertion_point(field_get:protos.GWRpcMeta.req)
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::GWMeta*>(
      &::protos::_GWMeta_default_instance_);
}
inline ::protos::GWMeta* GWRpcMeta::release_req() {
  // @@protoc_insertion_point(field_release:protos.GWRpcMeta.req)
  
  ::protos::GWMeta* temp = req_;
  req_ = nullptr;
  return temp;
}
inline ::protos::GWMeta* GWRpcMeta::mutable_req() {
  
  if (req_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::GWMeta>(GetArenaNoVirtual());
    req_ = p;
  }
  // @@protoc_insertion_point(field_mutable:protos.GWRpcMeta.req)
  return req_;
}
inline void GWRpcMeta::set_allocated_req(::protos::GWMeta* req) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete req_;
  }
  if (req) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      req = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, req, submessage_arena);
    }
    
  } else {
    
  }
  req_ = req;
  // @@protoc_insertion_point(field_set_allocated:protos.GWRpcMeta.req)
}

// .protos.WGMeta resp = 2;
inline bool GWRpcMeta::has_resp() const {
  return this != internal_default_instance() && resp_ != nullptr;
}
inline void GWRpcMeta::clear_resp() {
  if (GetArenaNoVirtual() == nullptr && resp_ != nullptr) {
    delete resp_;
  }
  resp_ = nullptr;
}
inline const ::protos::WGMeta& GWRpcMeta::resp() const {
  const ::protos::WGMeta* p = resp_;
  // @@protoc_insertion_point(field_get:protos.GWRpcMeta.resp)
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::WGMeta*>(
      &::protos::_WGMeta_default_instance_);
}
inline ::protos::WGMeta* GWRpcMeta::release_resp() {
  // @@protoc_insertion_point(field_release:protos.GWRpcMeta.resp)
  
  ::protos::WGMeta* temp = resp_;
  resp_ = nullptr;
  return temp;
}
inline ::protos::WGMeta* GWRpcMeta::mutable_resp() {
  
  if (resp_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::WGMeta>(GetArenaNoVirtual());
    resp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:protos.GWRpcMeta.resp)
  return resp_;
}
inline void GWRpcMeta::set_allocated_resp(::protos::WGMeta* resp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete resp_;
  }
  if (resp) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      resp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, resp, submessage_arena);
    }
    
  } else {
    
  }
  resp_ = resp;
  // @@protoc_insertion_point(field_set_allocated:protos.GWRpcMeta.resp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_meta_2eproto
